ext_proc: fix proto which is causing build failures (#42872)
## Description

This PR fixes a build failure in ExtProc which is probably caused due to
a race condition while merging changes.

```
external/envoy_api/envoy/service/ext_proc/v3/external_processor.proto:252:24: Field number 11 has already been used in "envoy.service.ext_proc.v3.ProcessingResponse" by field "streamed_immediate_response". Next available field number is 12.
INFO: Elapsed time: 15.256s, Critical Path: 2.08s
INFO: 178 processes: 165 remote cache hit, 13 internal.
ERROR: Build did NOT complete successfully
ERROR: No test targets were found, yet testing was requested
```

---

**Commit Message:** ext_proc: fix proto which is causing build failures
**Additional Description:** Fix ExtProc failing build.
**Risk Level:** Low
**Testing:** CI
**Docs Changes:** N/A
**Release Notes:** N/A

Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>

Mirrored from https://github.com/envoyproxy/envoy @ 026090ca462a6bb01c5627bba4441eda7eceab11