ext_proc: Remove extra spaces from proto comments causing git-push failure. (#42809)
<!--
!!!ATTENTION!!!

If you are fixing *any* crash or *any* potential security issue, *do
not*
open a pull request in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged
appropriately.
Thank you in advance for helping to keep Envoy secure.

!!!ATTENTION!!!

For an explanation of how to fill out the fields, please see the
relevant section
in
[PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

!!!ATTENTION!!!

Please check the [use of generative AI
policy](https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md?plain=1#L41).

You may use generative AI only if you fully understand the code. You
need to disclose
this usage in the PR description to ensure transparency.
-->

Commit Message: Remove extra spaces from proto comments causing git-push
failure.
Additional Description: After pulling latest main, git-push started
failing with this error
```
ERROR: From ./api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto
ERROR: ./api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto:125: over-enthusiastic spaces
ERROR: From ./api/envoy/service/ext_proc/v3/external_processor.proto
ERROR: ./api/envoy/service/ext_proc/v3/external_processor.proto:230: over-enthusiastic spaces
ERROR: ./api/envoy/service/ext_proc/v3/external_processor.proto:233: over-enthusiastic spaces
```
I've removed the culprit extra-spaces from the proto. This was possibly
caused by merging #38753

Risk Level: None. Only proto comment changes.
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API
Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

Signed-off-by: Sumit Kumar <sumitkmr@google.com>

Mirrored from https://github.com/envoyproxy/envoy @ cbb043636653e92ec5dbf3c107f3e34123bcb0ca